# Generated by Django 5.0.7 on 2024-10-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_studentlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentList',
            new_name='patient_list',
        ),
    ]
